# Generated by Django 3.Raznoe on 2019-12-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_actual_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actual_news',
            options={'verbose_name': 'Актуальное событие', 'verbose_name_plural': 'Актуальные события'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
