# Generated by Django 3.Raznoe on 2019-12-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(max_length=200, verbose_name='telegram'),
        ),
    ]
