# Generated by Django 3.Raznoe on 2019-12-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20191219_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
