# Generated by Django 3.Raznoe on 2019-12-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actual_news',
            options={'verbose_name': 'Последняя новость', 'verbose_name_plural': 'Последние новости'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
