# Generated by Django 3.Raznoe on 2020-05-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20191220_0549'),
        ('landing', '0006_auto_20191220_0744'),
    ]

    operations = [
    ]
