# Generated by Django 3.Raznoe on 2020-05-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgc_solar_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='consumables_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='items_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='log_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='player_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quests_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uniq_items_data',
            field=models.TextField(default=''),
        ),
    ]
